import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useCallback, useState } from "react";
import { eye, eyeSlash } from "../components/utils/icon";

function Login() {
  const [user, setUser] = useState({ username: "", password: "" });
  const [isVisible, setIsVisible] = useState(false);
  const router = useRouter();

  const submit = useCallback(
    (e) => {
      e.preventDefault();

      axios
        .post("/auth/session", user)
        .then((res) => router.push(router.query.next ?? "/"))
        .catch((error) => console.log(error));
    },
    [user]
  );

  const handlePassword = useCallback(() => {
    setIsVisible(!isVisible);
  }, [isVisible]);

  const userChange = useCallback(
    (e) => {
      setUser((prev) => ({ ...prev, username: e.target.value }));
    },
    [user]
  );
  const passwordChange = useCallback(
    (e) => {
      setUser((prev) => ({ ...prev, password: e.target.value }));
    },
    [user]
  );

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen place-items-center grid grid-cols-2">
        <div>
          <img className="h-screen" src="./login.png" />
        </div>
        <div className="px-12 py-16 bg-white shadow-md border rounded-xl">
          <form className="flex flex-col w-96" onSubmit={submit}>
            <p className="font-bold text-2xl text-center">
              Sign up to <span className=" text-orange-500">be</span>talk
            </p>
            <input
              value={user.username}
              className="border-b-2 mt-16 focus:border-orange-500 p-2 outline-none"
              type={"text"}
              placeholder="Email or phone"
              onChange={userChange}
            />
            <div className="relative">
              <div className="absolute bottom-2 right-2">
                <div
                  className="select-none w-6 h-6 cursor-pointer fill-gray-500"
                  onClick={handlePassword}
                >
                  {!isVisible ? eye : eyeSlash}
                </div>
              </div>
              <input
                value={user.password}
                className="border-b-2 w-full mt-6 focus:border-orange-500 p-2 outline-none"
                type={isVisible ? "text" : "password"}
                placeholder="Password"
                onChange={passwordChange}
              />
            </div>
            <div className="flex mt-3 justify-end">
              <Link href={"/login"}>
                <a className="text-xs text-orange-500 font-semibold">
                  Forgot your password?
                </a>
              </Link>
            </div>
            <input
              className="rounded cursor-pointer mt-16 bg-orange-500 text-white py-2.5"
              type={"submit"}
              value="Submit"
            />
          </form>
        </div>
      </div>
    </>
  );
}

export default Login;
